name: "Fire and Lion"
description: "The art of storytelling and design"

url: http://localhost:4000
baseurl: /fireandlion
liveurl: http://fireandlion.com

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: "images/fire-and-lion-avatar.png"
      layout: "default"