# Only store settings here tht must be in config.yml,
# otherwise put them in _data/settings.yml.

# Set baseurl mainly for GitHub Pages URL
baseurl: /fireandlion

# Set pretty permalinks, not Jekyll default 'date'
permalink: pretty

# Set default page layout for all pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
