name: "Fire and Lion"
description: "Longform storytelling and design"

url: http://localhost:4000
baseurl: /fireandlion
liveurl: http://fireandlion.com
markdown: kramdown
permalink: pretty
highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: "fire-and-lion-avatar.png"
      layout: "default"
